n1 = int(input("Digite um valor: "))
n2 = int(input("Digite outro valor: "))
s = (n1 + n2)
p = (n1 * n2)
d = (n1 / n2)
di = (n1 // n2)
e = (n1 ** n2)
print("A soma vale {}, o produto vale {} e a divisão vale {:.1f}".format(s, p, d), end="; ")
print("A divisão inteira vale {} e a potência vale {}".format(di, e))
